root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - eslint-plugin-tsdoc
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier
  - prettier/@typescript-eslint
rules:
  quotes:
    - error
    - single
  import/no-unresolved:
    - error
    - ignore:
      - ^..$
      - ^../../lib
  import/order: error
  tsdoc/syntax: error
