language: node_js
node_js:
- node
- lts/*
before_install:
- rvm install 2.6.3
- ruby -v
- gem install bundler
install:
- npm ci
- bundler install
before_script:
- npm run clean
script:
- npm run build
- npm run test -- --reporter dot
- npm run example
before_deploy:
- npm run clean
- NODE_ENV=production npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: dev.ukatama@gmail.com
  api_key:
    secure: gmTZsF9toHSf2Vo7p8RoJFftIvyOQM9UXlMTCMeycEp8jeCJ9EzfYvuTsihiBTwbJgwU+Yv+HgY6JgshZKktpxo1R8hXuDUPax4MWZD7gpX+mByaFP1DQwgQCuS+BYS2w3zIaGJArjcPmU8UZbDffkPWgD089ctFLbHzzAKLPBVyKsOx+a5KXvW4OzlNV98qomfMjXpiGJaxlQMsYkA4g/ut5cUR9nXn3uar62G8aKuzUDiTvu/nZuJgrrDW79qmR+kvuIOnMQQtmkVshFdqxL6qIhpuq+4ZD/xw49louP/zhy6cFJDokQlpqB1kfdhBEHrSwff6SuYF7yeSuI29VVORa24qRvWFg39gfTb1QA18UTDB0IWSfJXbOg0nQVNb5qDDXGEJ6uwUmTjXPQJZ8KawVJtdRwiZhpgH6tqSy9nIH6Su57gqrRbxlDsq8qNq4c9Br8OMpVqACcB7m+1kwYhME1m8lsZBE0pHv/dzX+Gafe+0iZrwMVWaMe/qWu0/mj9nkIstNS3kJl1naB6PVYwtE5oruXXXOYDn73huJCnbYFdnKdbPihoSznDloUDfZwHe2B5BHnpDvGoM/gsA0Ok+afyBiBNQkTxViuzTYkikhg4lbuCEra0YFK8CJIZq5HpvGoaFJNbK/cZQZ1n1sGDdHd+Fqm789eYtcStlHao=
  on:
    tags: true
    repo: bcdice/bcdice-js
