language: node_js
node_js:
- node
- lts/*
before_install:
- rvm install 2.6.3
- ruby -v
- gem install bundler
install:
- npm ci
- bundler install
before_script:
- npm run clean
script:
- npm run lint
- npm run build
- npm run test
- npm run example
before_deploy:
- npm run clean
- NODE_ENV=production npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: dev.ukatama@gmail.com
  api_key:
    secure: "ZSGHpUn6QmFtMGmv96niSlfK43td1S6+a4tcWKiPAOk2H9apvbUc56E/FIngBl8PpTvP/s/ws3cuL7CYAAVv3h/orY/P+MvVyaj2gaYGZOs01Z306aSTguSfC8qlxNqriE2rwf0RPm7gpLe2a0ly2ovv6XOfm6oJ9am4anTIarufZhC6KT+EuMdVw84G5qRcoYVc0PftTMKSSf9NG0fOuAxngGvCVZb/mcIWv0pYpgYIQ/FWeVonZsEEQOUgaEj0asdiir/fEstmGx6ww4niXe3w1gNNH/SOpjwncGImtheLF3fRoc5OJhLTGtkjRMMuMyT+4t919sTX4UEp3u3rWnG1BX79Vt0/KBJiSdBoHidnxXKNN9pCYOzhv9quAUof9JoujJNl0pXqwn+bgEQMhZL7QotumWy/3IqoyjM5gHZBW+BPxABVjhXTCBPrgyjRoV9QrevNI16g0hI6KiRWlN/9i1p08M+rP8Wkif4g4dzGEbaA4EgZJ/dY2XQmmoWu3pKjL3HIl2/JDsql1zkWesFOifksUFhLeYJ2T5Cl4jRA6/yqrNXpBCEx0D8KgF86y1o6QMeVRUPt4ydA46wffDXgi9OOGsRHaniuppUnQjb/V+0D3ooxP3QsbKPjxfieEMG7dT8uvAqqup1UBpJFXQ5h0gGg4zQxkyIzP7LsntY="
  on:
    tags: true
    repo: bcdice/bcdice-js
