name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - lts/*
          - current
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true
    - run: npm ci
    - run: npm run clean
    - run: BUNDLE_PATH="$(pwd)/vendor/bundle" npm run build
    - run: npm run lint
    - run: npm test
    - run: npm run example

    - run: npm publish
      if: ${{ matrix.node-version == 'lts/*' && startsWith(github.ref, 'refs/tags/v') }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
