name: CI

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ matrix.node-version }}-${{ hashFiles('**/package.lock.json') }}
    - run: npm ci
    - run: npm run clean
    - run: npm run lint
    - run: BUNDLE_PATH="$(pwd)/../vendor/bundle" npm run build
    - run: npm test
    - run: npm run example

    - run: npm publish
      if: ${{ matrix.node-version == '10.x' && startsWith(github.ref, 'refs/tags/v') }}
